apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: microservices-project
  namespace: argocd
spec:
  description: CI/CD GitOps project for microservices on AKS
  sourceRepos:
    - "*"
  destinations:
    - namespace: microservices
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
