apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: microservices-project
  namespace: argocd
spec:
  description: CI/CD GitOps project for microservices on AKS
  sourceRepos:
    - "https://github.com/Ayooluwabami/cicd-azure-gitops-aks.git"
  destinations:
    - namespace: microservices
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: networking.k8s.io
      kind: Ingress
    - group: ""
      kind: Secret
