STUDENTS = [
    {"id": "STU001", "name": "Wisdom Uwaga",     "email": "wisdom@cloudboosta.ac",   "year": 2, "programme": "Cloud Engineering",  "status": "Active"},
    {"id": "STU002", "name": "Bolarinwa Akinde", "email": "bola@cloudboosta.ac",     "year": 3, "programme": "Cloud Engineering",  "status": "Active"},
    {"id": "STU003", "name": "Ayobami Edun",      "email": "ayo@cloudboosta.ac",      "year": 2, "programme": "DevOps Engineering", "status": "Active"},
    {"id": "STU004", "name": "Osahon Igbogbo",    "email": "osahon@cloudboosta.ac",   "year": 2, "programme": "Cloud Engineering",  "status": "Active"},
    {"id": "STU005", "name": "Emmanuel Ohuoha",   "email": "emma@cloudboosta.ac",     "year": 2, "programme": "DevOps Engineering", "status": "Active"},
    {"id": "STU006", "name": "Adaeze Okafor",     "email": "adaeze@cloudboosta.ac",   "year": 1, "programme": "Cloud Security",     "status": "Active"},
    {"id": "STU007", "name": "Chukwudi Eze",      "email": "chukwudi@cloudboosta.ac", "year": 3, "programme": "Cloud Engineering",  "status": "Active"},
    {"id": "STU008", "name": "Fatima Bello",      "email": "fatima@cloudboosta.ac",   "year": 2, "programme": "DevOps Engineering", "status": "Active"},
    {"id": "STU009", "name": "Tunde Adesanya",    "email": "tunde@cloudboosta.ac",    "year": 1, "programme": "Cloud Engineering",  "status": "Inactive"},
    {"id": "STU010", "name": "Ngozi Obi",         "email": "ngozi@cloudboosta.ac",    "year": 3, "programme": "Cloud Security",     "status": "Active"},
]

ENROLMENTS = [
    {"id": "ENR001", "studentId": "STU001", "courseId": "CLO101", "grade": "A", "status": "Active"},
    {"id": "ENR002", "studentId": "STU001", "courseId": "DEV201", "grade": "A", "status": "Active"},
    {"id": "ENR003", "studentId": "STU001", "courseId": "PY301",  "grade": "B", "status": "Active"},
    {"id": "ENR004", "studentId": "STU002", "courseId": "CLO101", "grade": "A", "status": "Active"},
    {"id": "ENR005", "studentId": "STU002", "courseId": "DEV201", "grade": "B", "status": "Active"},
    {"id": "ENR006", "studentId": "STU002", "courseId": "NET401", "grade": "A", "status": "Active"},
    {"id": "ENR007", "studentId": "STU003", "courseId": "CLO101", "grade": "B", "status": "Active"},
    {"id": "ENR008", "studentId": "STU003", "courseId": "DEV201", "grade": "A", "status": "Active"},
    {"id": "ENR009", "studentId": "STU003", "courseId": "PY301",  "grade": "A", "status": "Active"},
    {"id": "ENR010", "studentId": "STU004", "courseId": "CLO101", "grade": "B", "status": "Active"},
    {"id": "ENR011", "studentId": "STU004", "courseId": "LNX101", "grade": "B", "status": "Active"},
    {"id": "ENR012", "studentId": "STU004", "courseId": "SEC201", "grade": "C", "status": "Active"},
    {"id": "ENR013", "studentId": "STU005", "courseId": "CLO101", "grade": "A", "status": "Active"},
    {"id": "ENR014", "studentId": "STU005", "courseId": "DEV201", "grade": "A", "status": "Active"},
    {"id": "ENR015", "studentId": "STU005", "courseId": "NET401", "grade": "B", "status": "Active"},
    {"id": "ENR016", "studentId": "STU006", "courseId": "PY301",  "grade": "C", "status": "Active"},
    {"id": "ENR017", "studentId": "STU006", "courseId": "LNX101", "grade": "B", "status": "Active"},
    {"id": "ENR018", "studentId": "STU006", "courseId": "SEC201", "grade": "B", "status": "Active"},
    {"id": "ENR019", "studentId": "STU007", "courseId": "CLO101", "grade": "A", "status": "Active"},
    {"id": "ENR020", "studentId": "STU007", "courseId": "DEV201", "grade": "A", "status": "Active"},
    {"id": "ENR021", "studentId": "STU007", "courseId": "SEC201", "grade": "A", "status": "Active"},
    {"id": "ENR022", "studentId": "STU008", "courseId": "PY301",  "grade": "B", "status": "Active"},
    {"id": "ENR023", "studentId": "STU008", "courseId": "NET401", "grade": "B", "status": "Active"},
    {"id": "ENR024", "studentId": "STU008", "courseId": "LNX101", "grade": "A", "status": "Active"},
    {"id": "ENR025", "studentId": "STU009", "courseId": "CLO101", "grade": "C", "status": "Active"},
    {"id": "ENR026", "studentId": "STU009", "courseId": "DEV201", "grade": "C", "status": "Active"},
    {"id": "ENR027", "studentId": "STU010", "courseId": "CLO101", "grade": "A", "status": "Active"},
    {"id": "ENR028", "studentId": "STU010", "courseId": "DEV201", "grade": "B", "status": "Active"},
    {"id": "ENR029", "studentId": "STU010", "courseId": "PY301",  "grade": "A", "status": "Active"},
    {"id": "ENR030", "studentId": "STU010", "courseId": "NET401", "grade": "A", "status": "Active"},
]
